<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_JOIN TSF NETWORK HERE (httpswww.linkedin._51d66a</name>
   <tag></tag>
   <elementGuidId>d0257afd-3c76-4748-a223-66eeb0ecb20c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-map-marker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-map-marker</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;contact&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;agile_banner_bottom_grids&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;col-xs-2 agile_contact_grid_left&quot;]/i[@class=&quot;fa fa-map-marker&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
   </webElementXpaths>
</WebElementEntity>
